FROM node:12.18.2-stretch

LABEL MAINTAINER = 'melthaw@gmail.com(https://github.com/melthaw/yapi-docker)'

RUN mkdir /yapi && cd /yapi && wget https://github.com/YMFE/yapi/archive/master.zip && \
    unzip master.zip && mv yapi-master vendors && rm master.zip
RUN npm i -g node-gyp yapi-cli npm@latest && cd /yapi/vendors && npm i --production;

WORKDIR /yapi/vendors

COPY config.json /yapi/
COPY entrypoint.sh /usr/local/bin/
COPY .vimrc /root/

EXPOSE 3000

VOLUME /var/log

ENTRYPOINT ["entrypoint.sh"]